nama = input(" Masukkan nama : ")
umur = input("Masukkan umur : ")
alamat = input("Masukkan alaamt : ")
sekolah = input("Alamat sekolah : ")
jurusan = input("Jrusan : ")
semester = input("Semester  : ")
nim = input("Masukkan NIM : ")

print("Nama     : ",nama)
print("Umur     : ",umur)
print("Alamat   : ",alamat)
print("Sekolah  : ",sekolah)
print("Jurusan  : ",jurusan)
print("Semseter : ",semester)
print("NIM      : ",nim)